name: Feature Request
description: Suggest an idea or improvement for WhatSave
title: "[Feature] "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the following form to help us understand your idea.

  - type: input
    id: version
    attributes:
      label: App version
      description: What version of WhatSave are you using?
      placeholder: e.g. v2.1.0
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Describe the feature
      description: A clear and concise description of the feature you'd like to see.
      placeholder: I would like the app to...

  - type: textarea
    id: motivation
    attributes:
      label: Why is this feature important?
      description: Tell us why this would be helpful or valuable for users.
      placeholder: This would be useful because...

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you considered other solutions or workarounds?
      placeholder: Maybe something similar like...

  - type: checkboxes
    id: checked
    attributes:
      label: Checklist
      options:
        - label: I have checked if this feature request already exists
        - label: I am using the latest version available
        - label: I agree to follow this project's [Code of Conduct](https://github.com/mardous/WhatSave/blob/master/CODE_OF_CONDUCT.md)
